import React from 'react'

export default function ContractJob() {
  return (<>
    <h2>this is a ContractJob component</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est numquam ducimus error aspernatur possimus, eligendi officiis! A quis rem ab porro quia vero quo, odio accusamus unde debitis saepe esse blanditiis qui iusto, suscipit error deleniti provident doloremque omnis asperiores nisi consectetur excepturi cumque! Quas, molestias? Commodi ad repudiandae necessitatibus praesentium voluptate, nihil aliquid eaque debitis maiores, sapiente esse consequuntur illum voluptatum? Quas, corporis praesentium perspiciatis illum placeat quos, nobis excepturi voluptate dicta nulla ipsam labore alias aliquid odio deserunt, saepe enim? Eaque mollitia facilis tempore reiciendis excepturi doloremque iste ratione. Officia impedit adipisci eius iste libero, eaque consequatur similique voluptatibus magnam est dolore ipsa cumque fugiat accusamus alias quisquam itaque velit at aliquam dolorem, repudiandae placeat voluptate reiciendis. Asperiores, molestias doloribus officiis dolorum quibusdam dicta aliquam unde repudiandae praesentium libero, doloremque itaque debitis deleniti aspernatur repellat temporibus tenetur beatae aut nostrum consequatur earum ullam nemo. Sunt aut consequatur distinctio fugit nostrum dolore sint labore perferendis nihil ipsa, nemo tempora ab reprehenderit nisi, accusantium amet, culpa rem. Nisi modi illum non quaerat deserunt neque earum odio mollitia aperiam? Vero numquam praesentium qui nesciunt eum ex, aliquid excepturi consequatur id aperiam molestias tenetur cum ratione, repellendus itaque pariatur, dolores aliquam modi. Quisquam voluptates mollitia blanditiis at fugiat, deserunt rerum, sunt facilis sit fugit, pariatur dicta ad reiciendis impedit similique dolorem minus eum architecto quia! Beatae, cupiditate deserunt delectus a, sequi dignissimos aliquid nihil numquam molestias eos animi libero inventore, aut dolorem! Facilis a qui iste placeat maxime obcaecati beatae omnis tempora alias quisquam assumenda illo officiis nemo sapiente nobis, deserunt aliquid dolor at laudantium, nesciunt tempore quis! Quos voluptate itaque odio veritatis velit inventore, quidem voluptatum facilis cumque facere eos temporibus nesciunt accusamus debitis veniam. Minima dolores cumque eos eaque quis expedita quas, qui labore deleniti incidunt veritatis exercitationem mollitia dignissimos.</p>
  </>

  )
}
